version: '3.4'

services:
  auth.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  department.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  employee.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

