version: '3.4'

services:
  auth.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${ESHOP_AZURE_CATALOG_DB:-Server=10.0.75.1,1455;Database=MicroserviceDemo.Services.AuthDb;User Id=sa;Password=ProductApi(!);MultipleActiveResultSets=True}
    ports:
      - "4001:80"

  department.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${ESHOP_AZURE_CATALOG_DB:-Server=10.0.75.1,1455;Database=MicroserviceDemo.Services.DepartmentDb;User Id=sa;Password=ProductApi(!);MultipleActiveResultSets=True}
    ports:
      - "4002:80"


  employee.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${ESHOP_AZURE_CATALOG_DB:-Server=10.0.75.1,1455;Database=MicroserviceDemo.Services.EmployeeDb;User Id=sa;Password=ProductApi(!);MultipleActiveResultSets=True}
    ports:
      - "4003:80"


  mobileapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4100:80"
    volumes:
      - ./ApiGateways/Mobile.Bff/apigw:${DEMO_OCELOT_VOLUME_SPEC:-/app/configuration}

  webapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4101:80"
    volumes:
      - ./ApiGateways/Mobile.Bff/apigw:${DEMO_OCELOT_VOLUME_SPEC:-/app/configuration}


  mobileagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4200:80"

